### PR TITLE
Hotfix encoding issue

### LINKED ISSUE #96: UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-3: ordinal not in range(128)
Details
image

My data is about Chinese Math questions : 
小蓉吃了8顆水餃，小宇吃了10顆水餃，誰吃的水餃比較多？ (  )吃的多

And the training data is : 
小 小蓉 人名 B-人名
蓉 小蓉 人名 E-人名
吃 吃 VC S
了 了 Di S
8 8 Neu S
顆 顆 Nf S
水 水餃 Na S
餃 水餃 Na S
， ， COMMACATEGORY S
小 小宇 人名 B-人名
宇 小宇 人名 E-人名
吃 吃 VC S
了 了 Di S
1 10 Neu S
0 10 Neu S
顆 顆 Nf S
水 水餃 Na S
餃 水餃 Na S
， ， COMMACATEGORY S
誰 誰 Nh S
吃 吃 VC S
的 的 DE S
水 水餃 Na S
餃 水餃 Na S
比 比較 Dfa S
較 比較 Dfa S
多 多 VH S
？ ？ QUESTIONCATEGORY S
( ( PARENTHESISCATEGORY S
) ) PARENTHESISCATEGORY S
吃 吃 VC S
的 的 DE S
多 多 VH S

### PR DESCRIPTION
**Pull request by erip**
Closes #96 and #106

### CODE REVIEW

**Comment by erip** [comment]
cc @kmike - hopefully this can land in 0.9.8. Let me know if there's anything I can do to help that along. 😄

**Comment by erip** [comment]
I also wonder if this brings into question the desire to maintain python 2 support. Send it's officially EOL, do we want to remove it from CI? It would probably simplify the code quite a lot... that seems to be the issue with tests currently.

**Comment by BLKSerene** [comment]
I have the same issue here, I 've found the problem is `python-crfsuite` only recently. It would be great if this pull request could be merged and released.

**Comment by BLKSerene** [comment]
Any updates on this PR?

**Comment by fgregg** [comment]
thank you. closed with https://github.com/scrapinghub/python-crfsuite/commit/4014eb0244af8bdfbe58662e95acd7fb50bdb1e5

**Pull request closed without merging**
