### PR TITLE
merge crfsuite fix for windows installation

### PR DESCRIPTION
**Pull request by icoxfog417**
merge below crfsuite fix for windows installation.

[Updated some staffs so that MSVC 2015 can compile the source code](https://github.com/chokkan/crfsuite/commit/a5221daa150ecddb4f0656033275e4a1f91effd9)

### CODE REVIEW

**Comment by kmike** [comment]
If I'm not mistaken, this breaks building crfsuite on older MSVC, breaking python-crfsuite for all Pythons < 3.5 on Windows. See also: https://github.com/tpeng/python-crfsuite/pull/33, https://github.com/tpeng/python-crfsuite/pull/34.

**Comment by kmike** [comment]
Again, if I got it right, we're waiting for https://github.com/chokkan/crfsuite/pull/66 upstream change.

**Comment by icoxfog417** [comment]
Thank you for the confirmation! I agree chokka/crfsuite#66 is fundamental solution.

**Comment by fgregg** [comment]
This has been superseded by #66

**Comment by fgregg** [comment]
This can be closed.

**Comment by kmike** [comment]
👍

**Pull request closed without merging**
