### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel build support.
Related to #126 . @kmike Could you please review this PR?

### CODE REVIEW

**Comment by odidev** [comment]
@kmike, Could you please have a look at this PR?

**Comment by odidev** [comment]
@kmike, Could you please have a look at this PR?

**Comment by odidev** [comment]
@kmike, Could you please have a look at this PR? Thanks in advance.

**Comment by fgregg** [comment]
will be superseded by #140

**Comment by odidev** [comment]
@fgregg The [PR](https://github.com/scrapinghub/python-crfsuite/issues/140) mentioned by you did not contain the code for aarch64 wheel build and testing. I have modified the code and the wheel is built and tested successfully on aarch64. 

**Commit Link:** https://github.com/odidev/python-crfsuite/commit/94514e3dcd42122fdd0a694255e537b6135737a0 

**Github actions Link:** https://github.com/odidev/python-crfsuite/runs/6524746640?check_suite_focus=true 

If the changes looks good to you. I can raise a PR.

**Comment by fgregg** [comment]
sure @odidev, let's see a PR!

**Comment by odidev** [comment]
@fgregg I have raised a [PR](https://github.com/scrapinghub/python-crfsuite/pull/147). Please have a look.

**Pull request closed without merging**
