### PR TITLE
updated crfsuite submodule to include msvc 2015 fix, closes #51

### LINKED ISSUE #51: Problem with compiling for Python 3.5 under Windows 10 x64
I had a problem when tried to compile this library. The problem was the following:
Compiler said thet the following definitions from **python-crfsuite/crfsuite/include/os.h**  conflict with such definitions from system <math.h>:
`#define isfinite    _finite`
`#define snprintf    _snprintf`

I changed them to the following:
`#define my_isfinite    _finite`
`#define my_snprintf    _snprintf`
And also fixed all places in the library where these definitions are used, and then everything compiled perfectly.

### PR DESCRIPTION
**Pull request by fgregg**
This will close #51, #50, #26

### CODE REVIEW

**Comment by fgregg** [comment]
hi @kmike, this is ready for review. All window builds are now passing!!!!!

**Comment by fgregg** [comment]
the failures in travis are unrelated to this PR

**Comment by fgregg** [comment]
@kmike I went ahead and made some changes to the travis an manylinux script so now all tests are passing for all configs!

**Comment by kmike** [comment]
Hey @fgregg,

Thanks a lot, this is super-awesome!

**Comment by fgregg** [comment]
Great. Can you cut another release for pypi?

**Comment by kmike** [comment]
@fgregg yep, I was waiting for CI to finish.

**Comment by fgregg** [comment]
Looks like you might have forgotten to push a tag. That's what triggers pypi uploads.

**Comment by kmike** [comment]
I have pushed the tag when pushing the commit, you can see it on github (e.g. [here](https://github.com/scrapinghub/python-crfsuite/tags)) :(

**Pull request merged**
